# ============================================
# Issam : Configuration du serveur
# Auteur : Issam ABOUSSAKKINE
# ============================================
server.port=8085

# ============================================
# Issam : Désactivation du banner Spring Boot
# ============================================
spring.main.banner-mode=off

# ============================================
# Issam : Configuration Thymeleaf
# ============================================
spring.thymeleaf.enabled=true
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html