# Configuration du serveur - Issam ABOUSSAKKINE
server.port=8085

# Desactivation du banner Spring Boot
spring.main.banner-mode=off

# Activation de Thymeleaf pour les templates HTML
spring.thymeleaf.enabled=true

# Desactivation du cache pour le developpement
spring.thymeleaf.cache=false

# Emplacement des fichiers templates
spring.thymeleaf.prefix=classpath:/templates/

# Extension des fichiers templates
spring.thymeleaf.suffix=.html